// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Test_SuaBoPhan
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Test_SuaBoPhan - Use 'Test_SuaBoPhanParams' to pass parameters into this method.
        /// </summary>
        public void Test_SuaBoPhan()
        {
            #region Variable Declarations
            WinCell uIBP04Cell = this.UIHomeWindow.UIDgvBoPhanWindow.UIDataGridViewTable.UIRow0Row.UIBP04Cell;
            WinButton uIEDITButton = this.UIHomeWindow.UIEDITWindow.UIEDITButton;
            WinEdit uITxtTenBPEdit = this.UIHomeWindow.UITxtTenBPWindow.UITxtTenBPEdit;
            WinButton uISAVEButton = this.UIHomeWindow.UISAVEWindow.UISAVEButton;
            #endregion

            // Click 'BP04' cell
            Mouse.Click(uIBP04Cell, new Point(742, 17));

            // Click 'EDIT' button
            Mouse.Click(uIEDITButton, new Point(66, 44));

            // Type 'Nhân Viên Giao Hàng' in 'txtTenBP' text box
            uITxtTenBPEdit.Text = this.Test_SuaBoPhanParams.UITxtTenBPEditText;

            // Click 'SAVE' button
            Mouse.Click(uISAVEButton, new Point(113, 21));
        }
        
        /// <summary>
        /// Assert_SuaThanhCong - Use 'Assert_SuaThanhCongExpectedValues' to pass parameters into this method.
        /// </summary>
        public void Assert_SuaThanhCong()
        {
            #region Variable Declarations
            WinText uISửathànhcôngText = this.UIMessageBoxThanhCongWindow.UISửathànhcôngWindow.UISửathànhcôngText;
            #endregion

            // Verify that the 'Name' property of 'Sửa thành công.' label equals 'Sửa thành công.'
            Assert.AreEqual(this.Assert_SuaThanhCongExpectedValues.UISửathànhcôngTextName, uISửathànhcôngText.Name);
        }
        
        /// <summary>
        /// Assert_NullTT - Use 'Assert_NullTTExpectedValues' to pass parameters into this method.
        /// </summary>
        public void Assert_NullTT()
        {
            #region Variable Declarations
            WinText uIHãyđiềndữliệuđầyđủText = this.UIMessageBoxCustomWindow.UIHãyđiềndữliệuđầyđủWindow.UIHãyđiềndữliệuđầyđủText;
            #endregion

            // Verify that the 'Name' property of 'Hãy điền dữ liệu đầy đủ' label equals 'Hãy điền dữ liệu đầy đủ'
            Assert.AreEqual(this.Assert_NullTTExpectedValues.UIHãyđiềndữliệuđầyđủTextName, uIHãyđiềndữliệuđầyđủText.Name);
        }
        
        /// <summary>
        /// Assert_TenBPDaCo - Use 'Assert_TenBPDaCoExpectedValues' to pass parameters into this method.
        /// </summary>
        public void Assert_TenBPDaCo()
        {
            #region Variable Declarations
            WinText uITênbộphậnđãtồntạiText = this.UIMessageBoxCustomWindow.UIHãyđiềndữliệuđầyđủWindow.UITênbộphậnđãtồntạiText;
            #endregion

            // Verify that the 'Name' property of 'Tên bộ phận đã tồn tại.' label equals 'Tên bộ phận đã tồn tại.'
            Assert.AreEqual(this.Assert_TenBPDaCoExpectedValues.UITênbộphậnđãtồntạiTextName, uITênbộphậnđãtồntạiText.Name);
        }
        
        #region Properties
        public virtual Test_SuaBoPhanParams Test_SuaBoPhanParams
        {
            get
            {
                if ((this.mTest_SuaBoPhanParams == null))
                {
                    this.mTest_SuaBoPhanParams = new Test_SuaBoPhanParams();
                }
                return this.mTest_SuaBoPhanParams;
            }
        }
        
        public virtual Assert_SuaThanhCongExpectedValues Assert_SuaThanhCongExpectedValues
        {
            get
            {
                if ((this.mAssert_SuaThanhCongExpectedValues == null))
                {
                    this.mAssert_SuaThanhCongExpectedValues = new Assert_SuaThanhCongExpectedValues();
                }
                return this.mAssert_SuaThanhCongExpectedValues;
            }
        }
        
        public virtual Assert_NullTTExpectedValues Assert_NullTTExpectedValues
        {
            get
            {
                if ((this.mAssert_NullTTExpectedValues == null))
                {
                    this.mAssert_NullTTExpectedValues = new Assert_NullTTExpectedValues();
                }
                return this.mAssert_NullTTExpectedValues;
            }
        }
        
        public virtual Assert_TenBPDaCoExpectedValues Assert_TenBPDaCoExpectedValues
        {
            get
            {
                if ((this.mAssert_TenBPDaCoExpectedValues == null))
                {
                    this.mAssert_TenBPDaCoExpectedValues = new Assert_TenBPDaCoExpectedValues();
                }
                return this.mAssert_TenBPDaCoExpectedValues;
            }
        }
        
        public UIHomeWindow UIHomeWindow
        {
            get
            {
                if ((this.mUIHomeWindow == null))
                {
                    this.mUIHomeWindow = new UIHomeWindow();
                }
                return this.mUIHomeWindow;
            }
        }
        
        public UIMessageBoxThanhCongWindow UIMessageBoxThanhCongWindow
        {
            get
            {
                if ((this.mUIMessageBoxThanhCongWindow == null))
                {
                    this.mUIMessageBoxThanhCongWindow = new UIMessageBoxThanhCongWindow();
                }
                return this.mUIMessageBoxThanhCongWindow;
            }
        }
        
        public UIMessageBoxCustomWindow UIMessageBoxCustomWindow
        {
            get
            {
                if ((this.mUIMessageBoxCustomWindow == null))
                {
                    this.mUIMessageBoxCustomWindow = new UIMessageBoxCustomWindow();
                }
                return this.mUIMessageBoxCustomWindow;
            }
        }
        #endregion
        
        #region Fields
        private Test_SuaBoPhanParams mTest_SuaBoPhanParams;
        
        private Assert_SuaThanhCongExpectedValues mAssert_SuaThanhCongExpectedValues;
        
        private Assert_NullTTExpectedValues mAssert_NullTTExpectedValues;
        
        private Assert_TenBPDaCoExpectedValues mAssert_TenBPDaCoExpectedValues;
        
        private UIHomeWindow mUIHomeWindow;
        
        private UIMessageBoxThanhCongWindow mUIMessageBoxThanhCongWindow;
        
        private UIMessageBoxCustomWindow mUIMessageBoxCustomWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Test_SuaBoPhan'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class Test_SuaBoPhanParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Nhân Viên Giao Hàng' in 'txtTenBP' text box
        /// </summary>
        public string UITxtTenBPEditText = "Nhân Viên Giao Hàng";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Assert_SuaThanhCong'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class Assert_SuaThanhCongExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Name' property of 'Sửa thành công.' label equals 'Sửa thành công.'
        /// </summary>
        public string UISửathànhcôngTextName = "Sửa thành công.";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Assert_NullTT'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class Assert_NullTTExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Name' property of 'Hãy điền dữ liệu đầy đủ' label equals 'Hãy điền dữ liệu đầy đủ'
        /// </summary>
        public string UIHãyđiềndữliệuđầyđủTextName = "Hãy điền dữ liệu đầy đủ";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Assert_TenBPDaCo'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class Assert_TenBPDaCoExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Name' property of 'Tên bộ phận đã tồn tại.' label equals 'Tên bộ phận đã tồn tại.'
        /// </summary>
        public string UITênbộphậnđãtồntạiTextName = "Tên bộ phận đã tồn tại.";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHomeWindow : WinWindow
    {
        
        public UIHomeWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Home";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Home");
            #endregion
        }
        
        #region Properties
        public UIDgvBoPhanWindow UIDgvBoPhanWindow
        {
            get
            {
                if ((this.mUIDgvBoPhanWindow == null))
                {
                    this.mUIDgvBoPhanWindow = new UIDgvBoPhanWindow(this);
                }
                return this.mUIDgvBoPhanWindow;
            }
        }
        
        public UIEDITWindow UIEDITWindow
        {
            get
            {
                if ((this.mUIEDITWindow == null))
                {
                    this.mUIEDITWindow = new UIEDITWindow(this);
                }
                return this.mUIEDITWindow;
            }
        }
        
        public UITxtTenBPWindow UITxtTenBPWindow
        {
            get
            {
                if ((this.mUITxtTenBPWindow == null))
                {
                    this.mUITxtTenBPWindow = new UITxtTenBPWindow(this);
                }
                return this.mUITxtTenBPWindow;
            }
        }
        
        public UISAVEWindow UISAVEWindow
        {
            get
            {
                if ((this.mUISAVEWindow == null))
                {
                    this.mUISAVEWindow = new UISAVEWindow(this);
                }
                return this.mUISAVEWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIDgvBoPhanWindow mUIDgvBoPhanWindow;
        
        private UIEDITWindow mUIEDITWindow;
        
        private UITxtTenBPWindow mUITxtTenBPWindow;
        
        private UISAVEWindow mUISAVEWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIDgvBoPhanWindow : WinWindow
    {
        
        public UIDgvBoPhanWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "dgvBoPhan";
            this.WindowTitles.Add("Home");
            #endregion
        }
        
        #region Properties
        public UIDataGridViewTable UIDataGridViewTable
        {
            get
            {
                if ((this.mUIDataGridViewTable == null))
                {
                    this.mUIDataGridViewTable = new UIDataGridViewTable(this);
                }
                return this.mUIDataGridViewTable;
            }
        }
        #endregion
        
        #region Fields
        private UIDataGridViewTable mUIDataGridViewTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIDataGridViewTable : WinTable
    {
        
        public UIDataGridViewTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinTable.PropertyNames.Name] = "DataGridView";
            this.WindowTitles.Add("Home");
            #endregion
        }
        
        #region Properties
        public UIRow0Row UIRow0Row
        {
            get
            {
                if ((this.mUIRow0Row == null))
                {
                    this.mUIRow0Row = new UIRow0Row(this);
                }
                return this.mUIRow0Row;
            }
        }
        #endregion
        
        #region Fields
        private UIRow0Row mUIRow0Row;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIRow0Row : WinRow
    {
        
        public UIRow0Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinRow.PropertyNames.Value] = "BP04      ;Nhân Viên Bảo Vệ";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Home");
            #endregion
        }
        
        #region Properties
        public WinCell UIBP04Cell
        {
            get
            {
                if ((this.mUIBP04Cell == null))
                {
                    this.mUIBP04Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUIBP04Cell.SearchProperties[WinCell.PropertyNames.Value] = "BP04      ";
                    this.mUIBP04Cell.WindowTitles.Add("Home");
                    #endregion
                }
                return this.mUIBP04Cell;
            }
        }
        #endregion
        
        #region Fields
        private WinCell mUIBP04Cell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIEDITWindow : WinWindow
    {
        
        public UIEDITWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "mnusua";
            this.WindowTitles.Add("Home");
            #endregion
        }
        
        #region Properties
        public WinButton UIEDITButton
        {
            get
            {
                if ((this.mUIEDITButton == null))
                {
                    this.mUIEDITButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIEDITButton.SearchProperties[WinButton.PropertyNames.Name] = "EDIT";
                    this.mUIEDITButton.WindowTitles.Add("Home");
                    #endregion
                }
                return this.mUIEDITButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIEDITButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UITxtTenBPWindow : WinWindow
    {
        
        public UITxtTenBPWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtTenBP";
            this.WindowTitles.Add("Home");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtTenBPEdit
        {
            get
            {
                if ((this.mUITxtTenBPEdit == null))
                {
                    this.mUITxtTenBPEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtTenBPEdit.WindowTitles.Add("Home");
                    #endregion
                }
                return this.mUITxtTenBPEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtTenBPEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UISAVEWindow : WinWindow
    {
        
        public UISAVEWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "mnuluu";
            this.WindowTitles.Add("Home");
            #endregion
        }
        
        #region Properties
        public WinButton UISAVEButton
        {
            get
            {
                if ((this.mUISAVEButton == null))
                {
                    this.mUISAVEButton = new WinButton(this);
                    #region Search Criteria
                    this.mUISAVEButton.SearchProperties[WinButton.PropertyNames.Name] = "SAVE";
                    this.mUISAVEButton.WindowTitles.Add("Home");
                    #endregion
                }
                return this.mUISAVEButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUISAVEButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIMessageBoxThanhCongWindow : WinWindow
    {
        
        public UIMessageBoxThanhCongWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "MessageBoxThanhCong";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MessageBoxThanhCong");
            #endregion
        }
        
        #region Properties
        public UISửathànhcôngWindow UISửathànhcôngWindow
        {
            get
            {
                if ((this.mUISửathànhcôngWindow == null))
                {
                    this.mUISửathànhcôngWindow = new UISửathànhcôngWindow(this);
                }
                return this.mUISửathànhcôngWindow;
            }
        }
        #endregion
        
        #region Fields
        private UISửathànhcôngWindow mUISửathànhcôngWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UISửathànhcôngWindow : WinWindow
    {
        
        public UISửathànhcôngWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "Test";
            this.WindowTitles.Add("MessageBoxThanhCong");
            #endregion
        }
        
        #region Properties
        public WinText UISửathànhcôngText
        {
            get
            {
                if ((this.mUISửathànhcôngText == null))
                {
                    this.mUISửathànhcôngText = new WinText(this);
                    #region Search Criteria
                    this.mUISửathànhcôngText.SearchProperties[WinText.PropertyNames.Name] = "Sửa thành công.";
                    this.mUISửathànhcôngText.WindowTitles.Add("MessageBoxThanhCong");
                    #endregion
                }
                return this.mUISửathànhcôngText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUISửathànhcôngText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIMessageBoxCustomWindow : WinWindow
    {
        
        public UIMessageBoxCustomWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "MessageBoxCustom";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MessageBoxCustom");
            #endregion
        }
        
        #region Properties
        public UIHãyđiềndữliệuđầyđủWindow UIHãyđiềndữliệuđầyđủWindow
        {
            get
            {
                if ((this.mUIHãyđiềndữliệuđầyđủWindow == null))
                {
                    this.mUIHãyđiềndữliệuđầyđủWindow = new UIHãyđiềndữliệuđầyđủWindow(this);
                }
                return this.mUIHãyđiềndữliệuđầyđủWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIHãyđiềndữliệuđầyđủWindow mUIHãyđiềndữliệuđầyđủWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHãyđiềndữliệuđầyđủWindow : WinWindow
    {
        
        public UIHãyđiềndữliệuđầyđủWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "Test";
            this.WindowTitles.Add("MessageBoxCustom");
            #endregion
        }
        
        #region Properties
        public WinText UIHãyđiềndữliệuđầyđủText
        {
            get
            {
                if ((this.mUIHãyđiềndữliệuđầyđủText == null))
                {
                    this.mUIHãyđiềndữliệuđầyđủText = new WinText(this);
                    #region Search Criteria
                    this.mUIHãyđiềndữliệuđầyđủText.SearchProperties[WinText.PropertyNames.Name] = "Hãy điền dữ liệu đầy đủ";
                    this.mUIHãyđiềndữliệuđầyđủText.WindowTitles.Add("MessageBoxCustom");
                    #endregion
                }
                return this.mUIHãyđiềndữliệuđầyđủText;
            }
        }
        
        public WinText UITênbộphậnđãtồntạiText
        {
            get
            {
                if ((this.mUITênbộphậnđãtồntạiText == null))
                {
                    this.mUITênbộphậnđãtồntạiText = new WinText(this);
                    #region Search Criteria
                    this.mUITênbộphậnđãtồntạiText.SearchProperties[WinText.PropertyNames.Name] = "Tên bộ phận đã tồn tại.";
                    this.mUITênbộphậnđãtồntạiText.WindowTitles.Add("MessageBoxCustom");
                    #endregion
                }
                return this.mUITênbộphậnđãtồntạiText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIHãyđiềndữliệuđầyđủText;
        
        private WinText mUITênbộphậnđãtồntạiText;
        #endregion
    }
}
